#############################################################################
# Makefile for building: hd_demo
# Generated by qmake (2.01a) (Qt 4.8.6) on: Wed Jun 3 17:29:00 2020
# Project:  qt_test.pro
# Template: app
# Command: /usr/lib/arm-linux-gnueabihf/qt4/bin/qmake -o Makefile qt_test.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -std=c++11  $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/local/include/opencv -I../../work2/mutlcam_mbdas/kernel-headers -I../../work2/mutlcam_mbdas/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/arm-linux-gnueabihf -L/usr/local/lib -lopencv_core -lopencv_imgcodecs -lopencv_highgui -lopencv_imgproc -lopencv_videoio -lopencv_ml -lopencv_video -lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_flann -L/home/cubox/work2/mutlcam_mbdas/lib -lnxvidrc -lm $(OPENCVLIB) /home/cubox/work2/mutlcam_mbdas/libstatic/libion.a /home/cubox/work2/mutlcam_mbdas/libstatic/libv4l2-nexell.a /home/cubox/work2/mutlcam_mbdas/libstatic/libnxvmem.a /home/cubox/work2/mutlcam_mbdas/libstatic/libnxvpu.a /home/cubox/work2/mutlcam_mbdas/libstatic/libyuv2rgb_neon.a -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/arm-linux-gnueabihf/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		faceeventthread.cpp \
		serialComthread.cpp \
		log_util.cpp \
		MLX90640_API.cpp \
		MLX90640_LINUX_I2C_Driver.cpp \
		melesixthread.cpp moc_mainwindow.cpp \
		moc_faceeventthread.cpp \
		moc_serialComthread.cpp \
		moc_melesixthread.cpp
OBJECTS       = main.o \
		mainwindow.o \
		faceeventthread.o \
		serialComthread.o \
		log_util.o \
		MLX90640_API.o \
		MLX90640_LINUX_I2C_Driver.o \
		melesixthread.o \
		moc_mainwindow.o \
		moc_faceeventthread.o \
		moc_serialComthread.o \
		moc_melesixthread.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qt_test.pro
QMAKE_TARGET  = hd_demo
DESTDIR       = 
TARGET        = hd_demo

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qt_test.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/arm-linux-gnueabihf/libQtGui.prl \
		/usr/lib/arm-linux-gnueabihf/libQtCore.prl
	$(QMAKE) -o Makefile qt_test.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/arm-linux-gnueabihf/libQtGui.prl:
/usr/lib/arm-linux-gnueabihf/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile qt_test.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/hd_demo1.0.0 || $(MKDIR) .tmp/hd_demo1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/hd_demo1.0.0/ && $(COPY_FILE) --parents mainwindow.h faceeventthread.h yuv2rgb.neon.h serialComthread.h log_util.h MLX90640_API.h MLX90640_I2C_Driver.h melesixthread.h .tmp/hd_demo1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp faceeventthread.cpp serialComthread.cpp log_util.cpp MLX90640_API.cpp MLX90640_LINUX_I2C_Driver.cpp melesixthread.cpp .tmp/hd_demo1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/hd_demo1.0.0/ && (cd `dirname .tmp/hd_demo1.0.0` && $(TAR) hd_demo1.0.0.tar hd_demo1.0.0 && $(COMPRESS) hd_demo1.0.0.tar) && $(MOVE) `dirname .tmp/hd_demo1.0.0`/hd_demo1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/hd_demo1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_faceeventthread.cpp moc_serialComthread.cpp moc_melesixthread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_faceeventthread.cpp moc_serialComthread.cpp moc_melesixthread.cpp
moc_mainwindow.cpp: faceeventthread.h \
		serialComthread.h \
		melesixthread.h \
		MLX90640_API.h \
		mainwindow.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_faceeventthread.cpp: faceeventthread.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) faceeventthread.h -o moc_faceeventthread.cpp

moc_serialComthread.cpp: serialComthread.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) serialComthread.h -o moc_serialComthread.cpp

moc_melesixthread.cpp: MLX90640_API.h \
		melesixthread.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) melesixthread.h -o moc_melesixthread.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/arm-linux-gnueabihf/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		faceeventthread.h \
		serialComthread.h \
		melesixthread.h \
		MLX90640_API.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		faceeventthread.h \
		serialComthread.h \
		melesixthread.h \
		MLX90640_API.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

faceeventthread.o: faceeventthread.cpp faceeventthread.h \
		yuv2rgb.neon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o faceeventthread.o faceeventthread.cpp

serialComthread.o: serialComthread.cpp serialComthread.h \
		mainwindow.h \
		faceeventthread.h \
		melesixthread.h \
		MLX90640_API.h \
		log_util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialComthread.o serialComthread.cpp

log_util.o: log_util.cpp log_util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o log_util.o log_util.cpp

MLX90640_API.o: MLX90640_API.cpp MLX90640_I2C_Driver.h \
		MLX90640_API.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MLX90640_API.o MLX90640_API.cpp

MLX90640_LINUX_I2C_Driver.o: MLX90640_LINUX_I2C_Driver.cpp MLX90640_I2C_Driver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MLX90640_LINUX_I2C_Driver.o MLX90640_LINUX_I2C_Driver.cpp

melesixthread.o: melesixthread.cpp melesixthread.h \
		MLX90640_API.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o melesixthread.o melesixthread.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_faceeventthread.o: moc_faceeventthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_faceeventthread.o moc_faceeventthread.cpp

moc_serialComthread.o: moc_serialComthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialComthread.o moc_serialComthread.cpp

moc_melesixthread.o: moc_melesixthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_melesixthread.o moc_melesixthread.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

